server:
  host:
  port: 3000
  sessionSecret:
twilio:
  accountSid:
  authToken:
  fromNumber:
justgiving:
  url: http://v3-sandbox.justgiving.com
  apiUrl: https://api-sandbox.justgiving.com
  charity:
  appId:
password: